# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: JKerboeuf Portfolio
# Description of the Site
description: A customizable Jekyll portfolio theme
# URL of Image of the Site
site-image: /assets/images/banner.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: /assets/images/icon.png

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /assets/images/bg.png

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: julien.kerboeuf@gmail.com
facebook_username:
twitter_username: LePsychoPatate
instagram_username: lapsychopatate
linkedin_username: jkerboeuf
github_username:  JKerboeuf
youtube_channel_id:
reddit_username: PsychoPatate
behance_username:
dribbble_username:
spotify_username:

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: JKerboeuf

# Name of the Author
author-name: JKerboeuf
# URL for the Image of the Author
author-image: /assets/images/icon.png
# 60 Words About the Author
author-about: Jeune développeur passionné de jeux vidéo
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/JKerboeuf

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
