# WhatATheme
markdown: kramdown

# URL of the Site
url: ''

# Title of the Site
title: JKerboeuf
# Description of the Site
description: "Welcome to my website ! It serves as my portfolio and my blog where you can check out my works and keep yourself up-to-date about everything I do."
# URL of Image of the Site
site-image: /assets/img/banner.jpg
# URL for the Image of custom Favicon
favicon-url: /assets/img/favicon.ico
# Keywords of the Site
site-keywords: Site, Portfolio, Blog, Dev, Video Game, Software, Code, Jeux Vidéos, Programmation
# Default language
locale: fr

# External CSS & JS
bootstrap-css: https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css
bootstrap-js: https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js
jquery: https://code.jquery.com/jquery-3.7.1.min.js
fontawesome: https://kit.fontawesome.com/0a7f15ecf5.js
flagicons: https://cdn.jsdelivr.net/gh/lipis/flag-icons@6.6.6/css/flag-icons.min.css

# Social Media and Contact
twitter_username: LePsychoPatate
instagram_username: lapsychopatate
linkedin_username: jkerboeuf
github_username:  JKerboeuf
reddit_username: PsychoPatate

# Google Analytics
google-analytics: G-PZ0L3V5ZS7
# Disqus
disqus-shortname: JKerboeuf

# Name of the Author
author-name: JKerboeuf
# URL for the Image of the Author
author-image: /assets/img/logo-circle.png
# 60 Words About the Author
author-about: Versatile and very creative, I aspire to become a video game developer. I am a French student living in Lille, and I have big plans for my future and ongoing projects.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/JKerboeuf

# SASS
sass:
  sass_dir: assets/sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "/:categories/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
