# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: JKerboeuf
# Description of the Site
description: Work in progress
# URL of Image of the Site
site-image: /assets/img/banner.jpg
# URL for the Image of custom Favicon
favicon-url: /assets/img/favicon.ico
# Keywords of the Site
site-keywords: Site, Portfolio

# External CSS & JS
bootstrap-css: https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css
bootstrap-js: https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js
jquery: https://code.jquery.com/jquery-3.7.1.min.js
fontawesome: https://kit.fontawesome.com/0a7f15ecf5.js
flagicons: https://cdn.jsdelivr.net/gh/lipis/flag-icons@6.6.6/css/flag-icons.min.css

# Social Media and Contact
email: julien.kerboeuf@gmail.com
facebook_username:
twitter_username: LePsychoPatate
instagram_username: lapsychopatate
linkedin_username: jkerboeuf
github_username:  JKerboeuf
youtube_channel_id:
reddit_username: PsychoPatate

# Google Analytics
google-analytics: G-PZ0L3V5ZS7
# Disqus
disqus-shortname: JKerboeuf

# Name of the Author
author-name: JKerboeuf
# URL for the Image of the Author
author-image: /assets/img/logo-circle.png
# 60 Words About the Author
author-about: Young French developper who loves video games
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/JKerboeuf

# SASS
sass:
  sass_dir: assets/sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "feed/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
